// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class GridContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject gridContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.GridContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PastedData("PastedData"),
		ShowEditMode("ShowEditMode"),
		ShowDarkTheme("ShowDarkTheme"),
		GridContext_GridItem("MyFirstModule.GridContext_GridItem"),
		GridContext_GridItem_SelectedSingle("MyFirstModule.GridContext_GridItem_SelectedSingle"),
		GridContext_GridItem_SelectedMultiple("MyFirstModule.GridContext_GridItem_SelectedMultiple");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GridContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GridContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject gridContextMendixObject)
	{
		if (gridContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!gridContextMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.gridContextMendixObject = gridContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.GridContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.GridContext(context, mendixObject);
	}

	public static myfirstmodule.proxies.GridContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.GridContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of PastedData
	 */
	public final java.lang.String getPastedData()
	{
		return getPastedData(getContext());
	}

	/**
	 * @param context
	 * @return value of PastedData
	 */
	public final java.lang.String getPastedData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PastedData.toString());
	}

	/**
	 * Set value of PastedData
	 * @param pasteddata
	 */
	public final void setPastedData(java.lang.String pasteddata)
	{
		setPastedData(getContext(), pasteddata);
	}

	/**
	 * Set value of PastedData
	 * @param context
	 * @param pasteddata
	 */
	public final void setPastedData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String pasteddata)
	{
		getMendixObject().setValue(context, MemberNames.PastedData.toString(), pasteddata);
	}

	/**
	 * @return value of ShowEditMode
	 */
	public final java.lang.Boolean getShowEditMode()
	{
		return getShowEditMode(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowEditMode
	 */
	public final java.lang.Boolean getShowEditMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowEditMode.toString());
	}

	/**
	 * Set value of ShowEditMode
	 * @param showeditmode
	 */
	public final void setShowEditMode(java.lang.Boolean showeditmode)
	{
		setShowEditMode(getContext(), showeditmode);
	}

	/**
	 * Set value of ShowEditMode
	 * @param context
	 * @param showeditmode
	 */
	public final void setShowEditMode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showeditmode)
	{
		getMendixObject().setValue(context, MemberNames.ShowEditMode.toString(), showeditmode);
	}

	/**
	 * @return value of ShowDarkTheme
	 */
	public final java.lang.Boolean getShowDarkTheme()
	{
		return getShowDarkTheme(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowDarkTheme
	 */
	public final java.lang.Boolean getShowDarkTheme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowDarkTheme.toString());
	}

	/**
	 * Set value of ShowDarkTheme
	 * @param showdarktheme
	 */
	public final void setShowDarkTheme(java.lang.Boolean showdarktheme)
	{
		setShowDarkTheme(getContext(), showdarktheme);
	}

	/**
	 * Set value of ShowDarkTheme
	 * @param context
	 * @param showdarktheme
	 */
	public final void setShowDarkTheme(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showdarktheme)
	{
		getMendixObject().setValue(context, MemberNames.ShowDarkTheme.toString(), showdarktheme);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GridContext_GridItem
	 */
	public final java.util.List<myfirstmodule.proxies.GridItem> getGridContext_GridItem() throws com.mendix.core.CoreException
	{
		return getGridContext_GridItem(getContext());
	}

	/**
	 * @param context
	 * @return value of GridContext_GridItem
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.GridItem> getGridContext_GridItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.GridItem> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.GridContext_GridItem.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(myfirstmodule.proxies.GridItem.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of GridContext_GridItem
	 * @param gridcontext_griditem
	 */
	public final void setGridContext_GridItem(java.util.List<myfirstmodule.proxies.GridItem> gridcontext_griditem)
	{
		setGridContext_GridItem(getContext(), gridcontext_griditem);
	}

	/**
	 * Set value of GridContext_GridItem
	 * @param context
	 * @param gridcontext_griditem
	 */
	public final void setGridContext_GridItem(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.GridItem> gridcontext_griditem)
	{
		var identifiers = gridcontext_griditem
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.GridContext_GridItem.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GridContext_GridItem_SelectedSingle
	 */
	public final myfirstmodule.proxies.GridItem getGridContext_GridItem_SelectedSingle() throws com.mendix.core.CoreException
	{
		return getGridContext_GridItem_SelectedSingle(getContext());
	}

	/**
	 * @param context
	 * @return value of GridContext_GridItem_SelectedSingle
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.GridItem getGridContext_GridItem_SelectedSingle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.GridItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GridContext_GridItem_SelectedSingle.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.GridItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GridContext_GridItem_SelectedSingle
	 * @param gridcontext_griditem_selectedsingle
	 */
	public final void setGridContext_GridItem_SelectedSingle(myfirstmodule.proxies.GridItem gridcontext_griditem_selectedsingle)
	{
		setGridContext_GridItem_SelectedSingle(getContext(), gridcontext_griditem_selectedsingle);
	}

	/**
	 * Set value of GridContext_GridItem_SelectedSingle
	 * @param context
	 * @param gridcontext_griditem_selectedsingle
	 */
	public final void setGridContext_GridItem_SelectedSingle(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.GridItem gridcontext_griditem_selectedsingle)
	{
		if (gridcontext_griditem_selectedsingle == null) {
			getMendixObject().setValue(context, MemberNames.GridContext_GridItem_SelectedSingle.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GridContext_GridItem_SelectedSingle.toString(), gridcontext_griditem_selectedsingle.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GridContext_GridItem_SelectedMultiple
	 */
	public final java.util.List<myfirstmodule.proxies.GridItem> getGridContext_GridItem_SelectedMultiple() throws com.mendix.core.CoreException
	{
		return getGridContext_GridItem_SelectedMultiple(getContext());
	}

	/**
	 * @param context
	 * @return value of GridContext_GridItem_SelectedMultiple
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.GridItem> getGridContext_GridItem_SelectedMultiple(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.GridItem> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.GridContext_GridItem_SelectedMultiple.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(myfirstmodule.proxies.GridItem.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of GridContext_GridItem_SelectedMultiple
	 * @param gridcontext_griditem_selectedmultiple
	 */
	public final void setGridContext_GridItem_SelectedMultiple(java.util.List<myfirstmodule.proxies.GridItem> gridcontext_griditem_selectedmultiple)
	{
		setGridContext_GridItem_SelectedMultiple(getContext(), gridcontext_griditem_selectedmultiple);
	}

	/**
	 * Set value of GridContext_GridItem_SelectedMultiple
	 * @param context
	 * @param gridcontext_griditem_selectedmultiple
	 */
	public final void setGridContext_GridItem_SelectedMultiple(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.GridItem> gridcontext_griditem_selectedmultiple)
	{
		var identifiers = gridcontext_griditem_selectedmultiple
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.GridContext_GridItem_SelectedMultiple.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return gridContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.GridContext that = (myfirstmodule.proxies.GridContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
