// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class GridItem implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject gridItemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.GridItem";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AutoNumberValue("AutoNumberValue"),
		BooleanValue("BooleanValue"),
		DateTimeValue("DateTimeValue"),
		DecimalValue("DecimalValue"),
		EnumValue("EnumValue"),
		IntegerValue("IntegerValue"),
		LongValue("LongValue"),
		StringValue("StringValue"),
		AllowEdit("AllowEdit"),
		GridItem_ReferencedItem("MyFirstModule.GridItem_ReferencedItem");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GridItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GridItem(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject gridItemMendixObject)
	{
		if (gridItemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, gridItemMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.gridItemMendixObject = gridItemMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.GridItem initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.GridItem(context, mendixObject);
	}

	public static myfirstmodule.proxies.GridItem load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.GridItem.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.GridItem> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.GridItem.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of AutoNumberValue
	 */
	public final java.lang.Long getAutoNumberValue()
	{
		return getAutoNumberValue(getContext());
	}

	/**
	 * @param context
	 * @return value of AutoNumberValue
	 */
	public final java.lang.Long getAutoNumberValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.AutoNumberValue.toString());
	}

	/**
	 * Set value of AutoNumberValue
	 * @param autonumbervalue
	 */
	public final void setAutoNumberValue(java.lang.Long autonumbervalue)
	{
		setAutoNumberValue(getContext(), autonumbervalue);
	}

	/**
	 * Set value of AutoNumberValue
	 * @param context
	 * @param autonumbervalue
	 */
	public final void setAutoNumberValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long autonumbervalue)
	{
		getMendixObject().setValue(context, MemberNames.AutoNumberValue.toString(), autonumbervalue);
	}

	/**
	 * @return value of BooleanValue
	 */
	public final java.lang.Boolean getBooleanValue()
	{
		return getBooleanValue(getContext());
	}

	/**
	 * @param context
	 * @return value of BooleanValue
	 */
	public final java.lang.Boolean getBooleanValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.BooleanValue.toString());
	}

	/**
	 * Set value of BooleanValue
	 * @param booleanvalue
	 */
	public final void setBooleanValue(java.lang.Boolean booleanvalue)
	{
		setBooleanValue(getContext(), booleanvalue);
	}

	/**
	 * Set value of BooleanValue
	 * @param context
	 * @param booleanvalue
	 */
	public final void setBooleanValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean booleanvalue)
	{
		getMendixObject().setValue(context, MemberNames.BooleanValue.toString(), booleanvalue);
	}

	/**
	 * @return value of DateTimeValue
	 */
	public final java.util.Date getDateTimeValue()
	{
		return getDateTimeValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTimeValue
	 */
	public final java.util.Date getDateTimeValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTimeValue.toString());
	}

	/**
	 * Set value of DateTimeValue
	 * @param datetimevalue
	 */
	public final void setDateTimeValue(java.util.Date datetimevalue)
	{
		setDateTimeValue(getContext(), datetimevalue);
	}

	/**
	 * Set value of DateTimeValue
	 * @param context
	 * @param datetimevalue
	 */
	public final void setDateTimeValue(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datetimevalue)
	{
		getMendixObject().setValue(context, MemberNames.DateTimeValue.toString(), datetimevalue);
	}

	/**
	 * @return value of DecimalValue
	 */
	public final java.math.BigDecimal getDecimalValue()
	{
		return getDecimalValue(getContext());
	}

	/**
	 * @param context
	 * @return value of DecimalValue
	 */
	public final java.math.BigDecimal getDecimalValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DecimalValue.toString());
	}

	/**
	 * Set value of DecimalValue
	 * @param decimalvalue
	 */
	public final void setDecimalValue(java.math.BigDecimal decimalvalue)
	{
		setDecimalValue(getContext(), decimalvalue);
	}

	/**
	 * Set value of DecimalValue
	 * @param context
	 * @param decimalvalue
	 */
	public final void setDecimalValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal decimalvalue)
	{
		getMendixObject().setValue(context, MemberNames.DecimalValue.toString(), decimalvalue);
	}

	/**
	 * Get value of EnumValue
	 * @param enumvalue
	 */
	public final myfirstmodule.proxies.RowColour getEnumValue()
	{
		return getEnumValue(getContext());
	}

	/**
	 * @param context
	 * @return value of EnumValue
	 */
	public final myfirstmodule.proxies.RowColour getEnumValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.EnumValue.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.RowColour.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of EnumValue
	 * @param enumvalue
	 */
	public final void setEnumValue(myfirstmodule.proxies.RowColour enumvalue)
	{
		setEnumValue(getContext(), enumvalue);
	}

	/**
	 * Set value of EnumValue
	 * @param context
	 * @param enumvalue
	 */
	public final void setEnumValue(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RowColour enumvalue)
	{
		if (enumvalue != null) {
			getMendixObject().setValue(context, MemberNames.EnumValue.toString(), enumvalue.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.EnumValue.toString(), null);
		}
	}

	/**
	 * @return value of IntegerValue
	 */
	public final java.lang.Integer getIntegerValue()
	{
		return getIntegerValue(getContext());
	}

	/**
	 * @param context
	 * @return value of IntegerValue
	 */
	public final java.lang.Integer getIntegerValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.IntegerValue.toString());
	}

	/**
	 * Set value of IntegerValue
	 * @param integervalue
	 */
	public final void setIntegerValue(java.lang.Integer integervalue)
	{
		setIntegerValue(getContext(), integervalue);
	}

	/**
	 * Set value of IntegerValue
	 * @param context
	 * @param integervalue
	 */
	public final void setIntegerValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer integervalue)
	{
		getMendixObject().setValue(context, MemberNames.IntegerValue.toString(), integervalue);
	}

	/**
	 * @return value of LongValue
	 */
	public final java.lang.Long getLongValue()
	{
		return getLongValue(getContext());
	}

	/**
	 * @param context
	 * @return value of LongValue
	 */
	public final java.lang.Long getLongValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.LongValue.toString());
	}

	/**
	 * Set value of LongValue
	 * @param longvalue
	 */
	public final void setLongValue(java.lang.Long longvalue)
	{
		setLongValue(getContext(), longvalue);
	}

	/**
	 * Set value of LongValue
	 * @param context
	 * @param longvalue
	 */
	public final void setLongValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long longvalue)
	{
		getMendixObject().setValue(context, MemberNames.LongValue.toString(), longvalue);
	}

	/**
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue()
	{
		return getStringValue(getContext());
	}

	/**
	 * @param context
	 * @return value of StringValue
	 */
	public final java.lang.String getStringValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StringValue.toString());
	}

	/**
	 * Set value of StringValue
	 * @param stringvalue
	 */
	public final void setStringValue(java.lang.String stringvalue)
	{
		setStringValue(getContext(), stringvalue);
	}

	/**
	 * Set value of StringValue
	 * @param context
	 * @param stringvalue
	 */
	public final void setStringValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stringvalue)
	{
		getMendixObject().setValue(context, MemberNames.StringValue.toString(), stringvalue);
	}

	/**
	 * @return value of AllowEdit
	 */
	public final java.lang.Boolean getAllowEdit()
	{
		return getAllowEdit(getContext());
	}

	/**
	 * @param context
	 * @return value of AllowEdit
	 */
	public final java.lang.Boolean getAllowEdit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AllowEdit.toString());
	}

	/**
	 * Set value of AllowEdit
	 * @param allowedit
	 */
	public final void setAllowEdit(java.lang.Boolean allowedit)
	{
		setAllowEdit(getContext(), allowedit);
	}

	/**
	 * Set value of AllowEdit
	 * @param context
	 * @param allowedit
	 */
	public final void setAllowEdit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean allowedit)
	{
		getMendixObject().setValue(context, MemberNames.AllowEdit.toString(), allowedit);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GridItem_ReferencedItem
	 */
	public final myfirstmodule.proxies.ReferencedItem getGridItem_ReferencedItem() throws com.mendix.core.CoreException
	{
		return getGridItem_ReferencedItem(getContext());
	}

	/**
	 * @param context
	 * @return value of GridItem_ReferencedItem
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.ReferencedItem getGridItem_ReferencedItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.ReferencedItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.GridItem_ReferencedItem.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.ReferencedItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of GridItem_ReferencedItem
	 * @param griditem_referenceditem
	 */
	public final void setGridItem_ReferencedItem(myfirstmodule.proxies.ReferencedItem griditem_referenceditem)
	{
		setGridItem_ReferencedItem(getContext(), griditem_referenceditem);
	}

	/**
	 * Set value of GridItem_ReferencedItem
	 * @param context
	 * @param griditem_referenceditem
	 */
	public final void setGridItem_ReferencedItem(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ReferencedItem griditem_referenceditem)
	{
		if (griditem_referenceditem == null) {
			getMendixObject().setValue(context, MemberNames.GridItem_ReferencedItem.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.GridItem_ReferencedItem.toString(), griditem_referenceditem.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return gridItemMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.GridItem that = (myfirstmodule.proxies.GridItem) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
