// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class GridContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject gridContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.GridContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ActionPayload("ActionPayload"),
		GridContext_GridItem("MyFirstModule.GridContext_GridItem");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public GridContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected GridContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject gridContextMendixObject)
	{
		if (gridContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, gridContextMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.gridContextMendixObject = gridContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.GridContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.GridContext(context, mendixObject);
	}

	public static myfirstmodule.proxies.GridContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.GridContext.initialize(context, mendixObject);
	}

	/**
	 * @return value of ActionPayload
	 */
	public final java.lang.String getActionPayload()
	{
		return getActionPayload(getContext());
	}

	/**
	 * @param context
	 * @return value of ActionPayload
	 */
	public final java.lang.String getActionPayload(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ActionPayload.toString());
	}

	/**
	 * Set value of ActionPayload
	 * @param actionpayload
	 */
	public final void setActionPayload(java.lang.String actionpayload)
	{
		setActionPayload(getContext(), actionpayload);
	}

	/**
	 * Set value of ActionPayload
	 * @param context
	 * @param actionpayload
	 */
	public final void setActionPayload(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actionpayload)
	{
		getMendixObject().setValue(context, MemberNames.ActionPayload.toString(), actionpayload);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of GridContext_GridItem
	 */
	public final java.util.List<myfirstmodule.proxies.GridItem> getGridContext_GridItem() throws com.mendix.core.CoreException
	{
		return getGridContext_GridItem(getContext());
	}

	/**
	 * @param context
	 * @return value of GridContext_GridItem
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.GridItem> getGridContext_GridItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.GridItem> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.GridContext_GridItem.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(myfirstmodule.proxies.GridItem.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of GridContext_GridItem
	 * @param gridcontext_griditem
	 */
	public final void setGridContext_GridItem(java.util.List<myfirstmodule.proxies.GridItem> gridcontext_griditem)
	{
		setGridContext_GridItem(getContext(), gridcontext_griditem);
	}

	/**
	 * Set value of GridContext_GridItem
	 * @param context
	 * @param gridcontext_griditem
	 */
	public final void setGridContext_GridItem(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.GridItem> gridcontext_griditem)
	{
		var identifiers = gridcontext_griditem
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.GridContext_GridItem.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return gridContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.GridContext that = (myfirstmodule.proxies.GridContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
