// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum RowColour
{
	Green("094d9fc2-b3ea-4bc9-89c1-e28f9111c1c0"),
	Red("de8c6d77-eb11-494f-82a5-075650689b2c"),
	Blue("e3181884-47a8-4870-a400-00941ca2cc1e");

	private final java.lang.String i18nCaptionKey;
	
	private RowColour(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
