// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class TestEntity implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject testEntityMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.TestEntity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TemplateSource("TemplateSource"),
		GeneratedPreview("GeneratedPreview");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TestEntity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TestEntity(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject testEntityMendixObject)
	{
		if (testEntityMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, testEntityMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.testEntityMendixObject = testEntityMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.TestEntity initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TestEntity(context, mendixObject);
	}

	public static myfirstmodule.proxies.TestEntity load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TestEntity.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.TestEntity> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.TestEntity.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of TemplateSource
	 */
	public final java.lang.String getTemplateSource()
	{
		return getTemplateSource(getContext());
	}

	/**
	 * @param context
	 * @return value of TemplateSource
	 */
	public final java.lang.String getTemplateSource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TemplateSource.toString());
	}

	/**
	 * Set value of TemplateSource
	 * @param templatesource
	 */
	public final void setTemplateSource(java.lang.String templatesource)
	{
		setTemplateSource(getContext(), templatesource);
	}

	/**
	 * Set value of TemplateSource
	 * @param context
	 * @param templatesource
	 */
	public final void setTemplateSource(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String templatesource)
	{
		getMendixObject().setValue(context, MemberNames.TemplateSource.toString(), templatesource);
	}

	/**
	 * @return value of GeneratedPreview
	 */
	public final java.lang.String getGeneratedPreview()
	{
		return getGeneratedPreview(getContext());
	}

	/**
	 * @param context
	 * @return value of GeneratedPreview
	 */
	public final java.lang.String getGeneratedPreview(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GeneratedPreview.toString());
	}

	/**
	 * Set value of GeneratedPreview
	 * @param generatedpreview
	 */
	public final void setGeneratedPreview(java.lang.String generatedpreview)
	{
		setGeneratedPreview(getContext(), generatedpreview);
	}

	/**
	 * Set value of GeneratedPreview
	 * @param context
	 * @param generatedpreview
	 */
	public final void setGeneratedPreview(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String generatedpreview)
	{
		getMendixObject().setValue(context, MemberNames.GeneratedPreview.toString(), generatedpreview);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return testEntityMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TestEntity that = (myfirstmodule.proxies.TestEntity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
