// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies;

public enum PictureQuality
{
	original("dbf220f0-86b4-42ab-ac05-ac2c5607f765"),
	low("c887dee0-9c90-40f4-9def-04f1a1180bbc"),
	medium("330e5916-6249-43c0-b1fa-5c6713173037"),
	high("38d1d6e6-7bc6-4b27-95a1-34a726d98925"),
	custom("d0ee54b2-436a-48ea-b575-6a9064d270b5");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
