// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_CreateReferencedItemListBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_CreateReferencedItemList");
		return builder;
	}

	public static void aCT_CreateReferencedItemList(IContext context)
	{
		aCT_CreateReferencedItemListBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SaveAllChangesBuilder(
		myfirstmodule.proxies.GridContext _gridContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_SaveAllChanges");
		builder = builder.withParam("GridContext", _gridContext);
		return builder;
	}

	public static void aCT_SaveAllChanges(
		IContext context,
		myfirstmodule.proxies.GridContext _gridContext
	)
	{
		aCT_SaveAllChangesBuilder(
				_gridContext
			)
			.execute(context);
	}
}
